export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

export const LOAD_MATCHES_SUCCESS = 'LOAD_MATCHES_SUCCESS';
export const LOAD_MATCHES_ERROR = 'LOAD_MATCHES_ERROR';

export const GET_DELIVERIES_SUCCESS = 'GET_DELIVERIES_SUCCESS';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_FAVORITE_SUCCESS = 'SET_FAVORITE_SUCCESS';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const STATUS_ERROR = 'STATUS_ERROR';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_RESET = 'STATUS_RESET';

export const MATCH_GET_SUCCESS = 'MATCH_GET_SUCCESS';
export const MATCH_UPDATE_SUCCESS = 'MATCH_UPDATE_SUCCESS';
export const MATCH_ADD_SUCCESS = 'MATCH_ADD_SUCCESS';

export const LOAD_DELIVERIES_SUCCESS = 'LOAD_DELIVERIES_SUCCESS';
export const LOAD_DELIVERIES_ERROR = 'LOAD_DELIVERIES_ERROR';

export const DELIVERY_GET_SUCCESS = 'DELIVERY_GET_SUCCESS';
export const DELIVERY_UPDATE_SUCCESS = 'DELIVERY_UPDATE_SUCCESS';
export const DELIVERY_ADD_SUCCESS = 'DELIVERY_ADD_SUCCESS';

export const PERFORMANCE_GET_SUCCESS = 'PERFORMANCE_GET_SUCCESS';
export const PERFORMANCE_UPDATE_SUCCESS = 'PERFORMANCE_UPDATE_SUCCESS';
export const PERFORMANCE_ADD_SUCCESS = 'PERFORMANCE_ADD_SUCCESS';

export const LOAD_TEAM_DATA_SUCCESS = 'LOAD_TEAM_DATA_SUCCESS';

